#!/usr/bin/env node

/**
 * Homeowners Platform Template - Interactive Setup Script
 * 
 * This script guides users through configuring their homeowner platform,
 * determining whether a static or server deployment is needed based on features.
 */

import { createInterface } from 'readline';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, relative } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = join(__dirname, '..');

// ANSI colors for terminal output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
};

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

function print(message, color = colors.reset) {
  console.log(`${color}${message}${colors.reset}`);
}

function printSection(title) {
  console.log();
  print(`═══════════════════════════════════════════════════════════`, colors.cyan);
  print(`  ${title}`, colors.bright);
  print(`═══════════════════════════════════════════════════════════`, colors.cyan);
  console.log();
}

// Recursively find all files in a directory
function getAllFiles(dir, files = []) {
  const entries = readdirSync(dir);
  for (const entry of entries) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      if (!['node_modules', '.next', '.git', 'out'].includes(entry)) {
        getAllFiles(fullPath, files);
      }
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

// Replace placeholders in file content
function replacePlaceholders(content, config) {
  return content
    .replace(/\{\{COMMUNITY_NAME\}\}/g, config.communityName)
    .replace(/\{\{DOMAIN\}\}/g, config.domain)
    .replace(/\{\{STATE\}\}/g, config.state)
    .replace(/\{\{STATE_STATUTE\}\}/g, config.stateStatute || 'your state statute')
    .replace(/\{\{LOT_COUNT\}\}/g, config.lotCount)
    .replace(/\{\{CITY_STATE\}\}/g, config.cityState)
    .replace(/\{\{RECALL_EMAIL\}\}/g, `recall@${config.domain}`);
}

// Generate .env.local content based on features
function generateEnvFile(config) {
  let env = `# ${config.communityName} - Environment Variables\n`;
  env += `# Generated by setup script\n\n`;

  if (config.features.aiChat) {
    env += `# AI Chat - Required for interactive chatbot\n`;
    env += `OPENAI_API_KEY=your_openai_api_key_here\n`;
    env += `PINECONE_API_KEY=your_pinecone_api_key_here\n`;
    env += `PINECONE_INDEX_NAME=your_index_name\n`;
    env += `NEXT_PUBLIC_SHOW_CHAT=true\n\n`;
  } else {
    env += `# AI Chat disabled - using static ChatGPT prompt instead\n`;
    env += `NEXT_PUBLIC_SHOW_CHAT=false\n\n`;
  }

  if (config.features.recall) {
    env += `# Recall Mechanism\n`;
    env += `NEXT_PUBLIC_SHOW_RECALL_BANNER=true\n`;
    env += `NEXT_PUBLIC_RECALL_ACTIVE=true\n\n`;

    if (config.features.emailForm) {
      env += `# Email Form - Required for proxy vote collection\n`;
      env += `RESEND_API_KEY=your_resend_api_key_here\n`;
      env += `NOTIFICATION_EMAIL=organizers@${config.domain}\n\n`;
    }
  } else {
    env += `# Recall Mechanism disabled\n`;
    env += `NEXT_PUBLIC_SHOW_RECALL_BANNER=false\n`;
    env += `NEXT_PUBLIC_RECALL_ACTIVE=false\n\n`;
  }

  return env;
}

async function main() {
  print(`\n🏠 Homeowners Platform Template Setup`, colors.bright);
  print(`   Configure your community platform\n`, colors.cyan);

  const config = {
    features: {},
  };

  // ═══════════════════════════════════════════════════════════
  // BASICS
  // ═══════════════════════════════════════════════════════════
  printSection('BASICS');

  config.communityName = await ask(`${colors.green}1.${colors.reset} Community name (e.g., "Sunset Ridge HOA"): `);
  if (!config.communityName) {
    print('Community name is required. Exiting.', colors.yellow);
    process.exit(1);
  }

  config.state = await ask(`${colors.green}2.${colors.reset} State (for legal references, e.g., "Oregon"): `);
  
  // Common state statute references for HOAs/planned communities
  const stateStatutes = {
    'alabama': 'Ala. Code §35-20',
    'alaska': 'AS §34.08',
    'arizona': 'ARS §33-1801',
    'arkansas': 'Ark. Code §18-13',
    'california': 'Civil Code §4000-6150 (Davis-Stirling Act)',
    'colorado': 'CCIOA (CRS §38-33.3)',
    'connecticut': 'CGS §47-200',
    'delaware': 'Del. Code §81',
    'florida': 'FS 720 (HOA Act)',
    'georgia': 'O.C.G.A. §44-3',
    'hawaii': 'HRS §421J',
    'idaho': 'Idaho Code §55-115',
    'illinois': '765 ILCS 160 (CICAA)',
    'indiana': 'IC §32-25.5',
    'iowa': 'Iowa Code §499B',
    'kansas': 'KSA §58-4601',
    'kentucky': 'KRS §381',
    'louisiana': 'La. R.S. §9:1141.1',
    'maine': 'Me. Rev. Stat. §33',
    'maryland': 'Md. Real Prop. §11B',
    'massachusetts': 'MGL c.183A',
    'michigan': 'MCL §559.101',
    'minnesota': 'Minn. Stat. §515B',
    'mississippi': 'Miss. Code §89-9',
    'missouri': 'RSMo §448',
    'montana': 'MCA §70-23',
    'nebraska': 'Neb. Rev. Stat. §76-825',
    'nevada': 'NRS 116',
    'new hampshire': 'RSA 356-B',
    'new jersey': 'NJSA 46:8B',
    'new mexico': 'NMSA §47-16',
    'new york': 'RPL §339',
    'north carolina': 'NCGS §47F (Planned Community Act)',
    'north dakota': 'NDCC §47-04.1',
    'ohio': 'ORC §5311',
    'oklahoma': 'Okla. Stat. §60-851',
    'oregon': 'ORS 94.550-94.783 (Planned Community Act)',
    'pennsylvania': '68 Pa.C.S. §5101 (UPCA)',
    'rhode island': 'RIGL §34-36.1',
    'south carolina': 'SC Code §27-30',
    'south dakota': 'SDCL §43-15A',
    'tennessee': 'Tenn. Code §66-27',
    'texas': 'Property Code §209 (HOA Act)',
    'utah': 'Utah Code §57-8a',
    'vermont': '27A V.S.A. §1-101',
    'virginia': 'Va. Code §55.1-1800 (POA Act)',
    'washington': 'RCW 64.38 (HOA Act)',
    'west virginia': 'W. Va. Code §36B',
    'wisconsin': 'Wis. Stat. §703',
    'wyoming': 'Wyo. Stat. §34-1',
    'district of columbia': 'DC Code §42-19',
  };
  config.stateStatute = stateStatutes[config.state.toLowerCase()] || '';
  
  if (!config.stateStatute) {
    print(`   ⚠ State statute not found for "${config.state}". You'll need to update {{STATE_STATUTE}} manually.`, colors.yellow);
  }
  
  config.domain = await ask(`${colors.green}3.${colors.reset} Domain name (e.g., "sunsetridge.homes"): `);
  config.cityState = await ask(`${colors.green}4.${colors.reset} City, State (e.g., "Portland, Oregon"): `);
  config.lotCount = await ask(`${colors.green}5.${colors.reset} Number of lots/units in community: `);

  // ═══════════════════════════════════════════════════════════
  // FEATURES
  // ═══════════════════════════════════════════════════════════
  printSection('FEATURES');

  const aiChatAnswer = await ask(`${colors.green}6.${colors.reset} Include AI chatbot trained on your docs? (y/n): `);
  config.features.aiChat = aiChatAnswer.toLowerCase() === 'y';

  if (config.features.aiChat) {
    print(`   → Requires: OpenAI API key, Pinecone for document embeddings`, colors.yellow);
    print(`   → Server deployment required (Vercel recommended)`, colors.yellow);
  } else {
    print(`   → Will include "Ask ChatGPT" button with pre-filled prompt`, colors.cyan);
  }

  const recallAnswer = await ask(`\n${colors.green}7.${colors.reset} Include recall/petition mechanism? (y/n): `);
  config.features.recall = recallAnswer.toLowerCase() === 'y';

  if (config.features.recall) {
    const emailFormAnswer = await ask(`${colors.green}8.${colors.reset} Collect proxy votes via email form? (y/n): `);
    config.features.emailForm = emailFormAnswer.toLowerCase() === 'y';

    if (config.features.emailForm) {
      print(`   → Requires: Resend API key for sending emails`, colors.yellow);
      print(`   → Server deployment required (Vercel recommended)`, colors.yellow);
    } else {
      print(`   → Will use mailto: links for manual proxy collection`, colors.cyan);
    }
  }

  // ═══════════════════════════════════════════════════════════
  // DEPLOYMENT MODE
  // ═══════════════════════════════════════════════════════════
  printSection('DEPLOYMENT');

  const needsServer = config.features.aiChat || config.features.emailForm;

  if (needsServer) {
    print(`📡 Server deployment required`, colors.yellow);
    print(`   Your selected features require server-side functionality.`);
    print(`   Recommended: Vercel (free tier available)`);
    print(`   Alternatives: Railway, Fly.io, AWS Amplify`);
  } else {
    print(`📄 Static deployment possible!`, colors.green);
    print(`   Your platform can be hosted anywhere that serves static files.`);
    print(`   Recommended: GitHub Pages, Netlify, Cloudflare Pages`);
    print(`   Benefits: Free hosting, no API costs, works offline`);
  }

  // ═══════════════════════════════════════════════════════════
  // APPLY CONFIGURATION
  // ═══════════════════════════════════════════════════════════
  printSection('APPLYING CONFIGURATION');

  const confirm = await ask(`Apply these settings? (y/n): `);
  if (confirm.toLowerCase() !== 'y') {
    print('Setup cancelled.', colors.yellow);
    rl.close();
    process.exit(0);
  }

  print(`\n⏳ Updating files with your configuration...`, colors.cyan);

  // Find and update all template files
  const files = getAllFiles(ROOT_DIR);
  let updatedCount = 0;

  for (const file of files) {
    if (file.endsWith('.ts') || file.endsWith('.tsx') || file.endsWith('.json') || file.endsWith('.md') || file.endsWith('.css')) {
      try {
        const content = readFileSync(file, 'utf-8');
        if (content.includes('{{')) {
          const updated = replacePlaceholders(content, config);
          if (updated !== content) {
            writeFileSync(file, updated);
            const relPath = relative(ROOT_DIR, file);
            print(`   ✓ Updated: ${relPath}`, colors.green);
            updatedCount++;
          }
        }
      } catch (err) {
        // Skip files that can't be read
      }
    }
  }

  // Generate .env.local files
  const envContent = generateEnvFile(config);
  writeFileSync(join(ROOT_DIR, 'apps/owners/.env.local'), envContent);
  print(`   ✓ Created: apps/owners/.env.local`, colors.green);

  if (config.features.recall) {
    writeFileSync(join(ROOT_DIR, 'apps/recall/.env.local'), envContent);
    print(`   ✓ Created: apps/recall/.env.local`, colors.green);
  }

  // Update next.config.js for static export if applicable
  if (!needsServer) {
    const nextConfigPath = join(ROOT_DIR, 'apps/owners/next.config.js');
    let nextConfig = readFileSync(nextConfigPath, 'utf-8');
    nextConfig = nextConfig.replace(
      "// output: 'export',",
      "output: 'export',"
    );
    writeFileSync(nextConfigPath, nextConfig);
    print(`   ✓ Enabled static export in next.config.js`, colors.green);
  }

  // ═══════════════════════════════════════════════════════════
  // NEXT STEPS
  // ═══════════════════════════════════════════════════════════
  printSection('SETUP COMPLETE!');

  print(`Updated ${updatedCount} files with your configuration.\n`);

  print(`Next steps:`, colors.bright);
  print(`  1. Install dependencies: pnpm install`);
  print(`  2. Update .env.local files with your API keys`);
  
  if (config.features.aiChat) {
    print(`  3. Add your governing documents to /docs folder`);
    print(`  4. Run embedding script: pnpm --filter owners embed`);
  }

  print(`  5. Start development: pnpm dev`);
  print(`  6. Deploy to ${needsServer ? 'Vercel' : 'your static host'}`);

  print(`\n📖 See README.md and docs/SETUP.md for detailed instructions.`, colors.cyan);
  print(`\n🏠 Good luck with your community platform!\n`, colors.green);

  rl.close();
}

main().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});

